# Generated by Django 4.2.2 on 2024-01-29 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('node1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='link_node1', to='airport.node')),
                ('node2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='link_node2', to='airport.node')),
            ],
        ),
    ]
