# Generated by Django 4.2.1 on 2024-01-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('1', 'RUNWAY'), ('2', 'TAXIWAY'), ('3', 'APRON')], default='2', max_length=2),
        ),
    ]
