# Generated by Django 4.2.1 on 2024-01-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='runway_designator',
            field=models.CharField(default='36', max_length=3),
        ),
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('1', 'INTERSECTION'), ('2', 'THRESHOLD/END'), ('3', 'DISPLACED THRESHOLD'), ('4', 'STOPBAR')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='node',
            name='z',
            field=models.FloatField(default='36'),
            preserve_default=False,
        ),
    ]
