# Generated by Django 4.2.1 on 2024-02-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_node_runway_designator_node_type_node_z'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='runway_designator',
            field=models.CharField(max_length=3),
        ),
    ]
