# Generated by Django 4.2.2 on 2024-02-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_alter_node_runway_designator'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='width',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
            preserve_default=False,
        ),
    ]
