# Generated by Django 4.2.2 on 2024-02-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0004_rename_landign_distance_aircraft_landing_distance'),
        ('airport', '0005_link_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft')),
                ('runway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.link')),
                ('threshold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.node')),
            ],
        ),
    ]
