# Generated by Django 4.2.1 on 2024-03-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_runway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxiway', models.CharField(max_length=2)),
                ('distance', models.FloatField()),
                ('angle', models.FloatField()),
                ('runway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.runway')),
            ],
        ),
    ]
