# Generated by Django 4.2.1 on 2024-01-25 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('icao_id', models.CharField(max_length=5)),
                ('app_speed', models.IntegerField()),
                ('mtow', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AircraftQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('aircrafts', models.ManyToManyField(through='fleet.AircraftQuantity', to='fleet.aircraft')),
            ],
        ),
        migrations.AddField(
            model_name='aircraftquantity',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.fleet'),
        ),
    ]
