# Generated by Django 4.2.1 on 2024-01-31 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='app_speed',
            new_name='landing_speed',
        ),
    ]
