# Generated by Django 4.2.1 on 2024-02-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_rename_app_speed_aircraft_landing_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='landign_distance',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
