# Generated by Django 4.2.1 on 2024-02-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_aircraft_landign_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='landign_distance',
            new_name='landing_distance',
        ),
    ]
