# Generated by Django 4.2.1 on 2024-03-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_rename_landign_distance_aircraft_landing_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDesignators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('type_designator', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('engine_type', models.CharField(max_length=50)),
                ('engine_count', models.CharField(max_length=1)),
                ('wtc', models.CharField(max_length=1)),
            ],
        ),
    ]
